In [1]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import time
from pprint import pprint
import csv
from scipy import stats

In [2]:
path = "911_calls_for_service.csv"
baltimore__911_df = pd.read_csv(path, low_memory=True, nrows=5000 )
baltimore__911_df.head()

,Unnamed: 0,callDateTime,priority,district,description,callNumber,incidentLocation,location
0,0,2015-07-13 10:41:00,Medium,CD,SEE TEXT,P151941002,0 N CALVERT ST,"(39.2899299,-76.6123462)"
1,1,2015-07-13 10:47:00,Medium,CD,911/NO VOICE,P151941003,600 E FAYETTE ST,"(39.2906737,-76.6071600)"
2,2,2015-07-13 10:42:00,Medium,CD,911/NO VOICE,P151941004,200 E BALTIMORE ST,"(39.2898910,-76.6120720)"
3,3,2015-07-13 10:45:00,Low,CD,PRKG COMPLAINT,P151941005,800 PARK AV,"(39.2985163,-76.6184754)"
4,4,2015-07-13 10:46:00,Medium,SW,AUTO THEFT,P151941006,3500 CLIFTON AV,"(39.3112130,-76.6763150)"

In [3]:
baltimore__911_df = baltimore__911_df.drop(columns=['Unnamed: 0'])
baltimore__911_df.head()

,callDateTime,priority,district,description,callNumber,incidentLocation,location
0,2015-07-13 10:41:00,Medium,CD,SEE TEXT,P151941002,0 N CALVERT ST,"(39.2899299,-76.6123462)"
1,2015-07-13 10:47:00,Medium,CD,911/NO VOICE,P151941003,600 E FAYETTE ST,"(39.2906737,-76.6071600)"
2,2015-07-13 10:42:00,Medium,CD,911/NO VOICE,P151941004,200 E BALTIMORE ST,"(39.2898910,-76.6120720)"
3,2015-07-13 10:45:00,Low,CD,PRKG COMPLAINT,P151941005,800 PARK AV,"(39.2985163,-76.6184754)"
4,2015-07-13 10:46:00,Medium,SW,AUTO THEFT,P151941006,3500 CLIFTON AV,"(39.3112130,-76.6763150)"

In [4]:
# type = baltimore__911_df["district"].value_counts()
# type

In [5]:
baltimore__911_df.rename(columns={'district':'District'}, inplace=True)
baltimore__911_df.head()

,callDateTime,priority,District,description,callNumber,incidentLocation,location
0,2015-07-13 10:41:00,Medium,CD,SEE TEXT,P151941002,0 N CALVERT ST,"(39.2899299,-76.6123462)"
1,2015-07-13 10:47:00,Medium,CD,911/NO VOICE,P151941003,600 E FAYETTE ST,"(39.2906737,-76.6071600)"
2,2015-07-13 10:42:00,Medium,CD,911/NO VOICE,P151941004,200 E BALTIMORE ST,"(39.2898910,-76.6120720)"
3,2015-07-13 10:45:00,Low,CD,PRKG COMPLAINT,P151941005,800 PARK AV,"(39.2985163,-76.6184754)"
4,2015-07-13 10:46:00,Medium,SW,AUTO THEFT,P151941006,3500 CLIFTON AV,"(39.3112130,-76.6763150)"

In [6]:
path = "BPD_Part_1_Victim_Based_Crime_Data.csv"
baltimore__crime_df = pd.read_csv(path, low_memory=True, nrows=5000  )
baltimore__crime_df.head()

,CrimeDate,CrimeTime,CrimeCode,Location,Description,Inside/Outside,Weapon,Post,District,Neighborhood,Longitude,Latitude,Location 1,Premise,Total Incidents
0,09/02/2017,23:30:00,3JK,4200 AUDREY AVE,ROBBERY - RESIDENCE,I,KNIFE,913,SOUTHERN,Brooklyn,-76.60541,39.22951,"(39.2295100000, -76.6054100000)",ROW/TOWNHO,1
1,09/02/2017,23:00:00,7A,800 NEWINGTON AVE,AUTO THEFT,O,NaN,133,CENTRAL,Reservoir Hill,-76.63217,39.31360,"(39.3136000000, -76.6321700000)",STREET,1
2,09/02/2017,22:53:00,9S,600 RADNOR AV,SHOOTING,Outside,FIREARM,524,NORTHERN,Winston-Govans,-76.60697,39.34768,"(39.3476800000, -76.6069700000)",Street,1
3,09/02/2017,22:50:00,4C,1800 RAMSAY ST,AGG. ASSAULT,I,OTHER,934,SOUTHERN,Carrollton Ridge,-76.64526,39.28315,"(39.2831500000, -76.6452600000)",ROW/TOWNHO,1
4,09/02/2017,22:31:00,4E,100 LIGHT ST,COMMON ASSAULT,O,HANDS,113,CENTRAL,Downtown West,-76.61365,39.28756,"(39.2875600000, -76.6136500000)",STREET,1

In [7]:
#extract year
baltimore__crime_df['year'] = pd.DatetimeIndex(baltimore__crime_df['CrimeDate']).year
baltimore__crime_df

,CrimeDate,CrimeTime,CrimeCode,Location,Description,Inside/Outside,Weapon,Post,District,Neighborhood,Longitude,Latitude,Location 1,Premise,Total Incidents,year
0,09/02/2017,23:30:00,3JK,4200 AUDREY AVE,ROBBERY - RESIDENCE,I,KNIFE,913,SOUTHERN,Brooklyn,-76.60541,39.22951,"(39.2295100000, -76.6054100000)",ROW/TOWNHO,1,2017
1,09/02/2017,23:00:00,7A,800 NEWINGTON AVE,AUTO THEFT,O,NaN,133,CENTRAL,Reservoir Hill,-76.63217,39.31360,"(39.3136000000, -76.6321700000)",STREET,1,2017
2,09/02/2017,22:53:00,9S,600 RADNOR AV,SHOOTING,Outside,FIREARM,524,NORTHERN,Winston-Govans,-76.60697,39.34768,"(39.3476800000, -76.6069700000)",Street,1,2017
3,09/02/2017,22:50:00,4C,1800 RAMSAY ST,AGG. ASSAULT,I,OTHER,934,SOUTHERN,Carrollton Ridge,-76.64526,39.28315,"(39.2831500000, -76.6452600000)",ROW/TOWNHO,1,2017
4,09/02/2017,22:31:00,4E,100 LIGHT ST,COMMON ASSAULT,O,HANDS,113,CENTRAL,Downtown West,-76.61365,39.28756,"(39.2875600000, -76.6136500000)",STREET,1,2017
5,09/02/2017,22:00:00,5A,CHERRYCREST RD,BURGLARY,I,NaN,922,SOUTHERN,Cherry Hill,-76.62131,39.24867,"(39.2486700000, -76.6213100000)",ROW/TOWNHO,1,2017
6,09/02/2017,21:15:00,1F,3400 HARMONY CT,HOMICIDE,Outside,FIREARM,232,SOUTHEASTERN,Canton,-76.56827,39.28202,"(39.2820200000, -76.5682700000)",Street,1,2017
7,09/02/2017,21:35:00,3B,400 W LANVALE ST,ROBBERY - STREET,O,NaN,123,CENTRAL,Upton,-76.62789,39.30254,"(39.3025400000, -76.6278900000)",STREET,1,2017
8,09/02/2017,21:00:00,4C,2300 LYNDHURST AVE,AGG. ASSAULT,O,OTHER,641,NORTHWESTERN,Windsor Hills,-76.68365,39.31370,"(39.3137000000, -76.6836500000)",STREET,1,2017
9,09/02/2017,21:00:00,4E,1200 N ELLWOOD AVE,COMMON ASSAULT,I,HANDS,332,EASTERN,Berea,-76.57419,39.30551,"(39.3055100000, -76.5741900000)",ROW/TOWNHO,1,2017
10,09/02/2017,21:00:00,4C,2300 LYNDHURST AVE,AGG. ASSAULT,O,OTHER,641,NORTHWESTERN,Windsor Hills,-76.68365,39.31370,"(39.3137000000, -76.6836500000)",STREET,1,2017
11,09/02/2017,20:56:00,3CF,3600 EDMONDSON AVE,ROBBERY - COMMERCIAL,I,FIREARM,844,SOUTHWESTERN,Edgewood,-76.67759,39.29402,"(39.2940200000, -76.6775900000)",RETAIL/SMA,1,2017
12,09/02/2017,20:55:00,6C,5100 PARK HEIGHTS AVE,LARCENY,NaN,NaN,614,NORTHWESTERN,Central Park Heights,-76.67511,39.34861,"(39.3486100000, -76.6751100000)",NaN,1,2017
13,09/02/2017,20:10:00,4C,3900 GWYNNS FALLS PKWY,AGG. ASSAULT,O,OTHER,641,NORTHWESTERN,Windsor Hills,-76.68169,39.31400,"(39.3140000000, -76.6816900000)",STREET,1,2017
14,09/02/2017,20:00:00,6D,5500 SUMMERFIELD AVE,LARCENY FROM AUTO,O,NaN,444,NORTHEASTERN,Frankford,-76.54270,39.33288,"(39.3328800000, -76.5427000000)",YARD,1,2017
15,09/02/2017,19:52:00,5D,2200 VAN DEMAN ST,BURGLARY,I,NaN,243,SOUTHEASTERN,Holabird Industrial Park,-76.53557,39.26533,"(39.2653300000, -76.5355700000)",OTHER - IN,1,2017
16,09/02/2017,18:08:00,9S,1200 E LAFAYETTE AV,SHOOTING,Outside,FIREARM,343,EASTERN,Oliver,-76.60246,39.31038,"(39.3103800000, -76.6024600000)",Street,1,2017
17,09/02/2017,18:08:00,1F,1200 E LAFAYETTE AV,HOMICIDE,Outside,FIREARM,343,EASTERN,Oliver,-76.60246,39.31038,"(39.3103800000, -76.6024600000)",Street,1,2017
18,09/02/2017,18:16:00,4E,1000 N EUTAW ST,COMMON ASSAULT,O,HANDS,132,CENTRAL,Madison Park,-76.62256,39.30083,"(39.3008300000, -76.6225600000)",STREET,1,2017
19,09/02/2017,18:00:00,6G,100 S BROADWAY,LARCENY,I,NaN,212,SOUTHEASTERN,Washington Hill,-76.59390,39.29020,"(39.2902000000, -76.5939000000)",CONVENIENC,1,2017
20,09/02/2017,17:17:00,5A,4000 RIDGECROFT RD,BURGLARY,I,NaN,426,NORTHEASTERN,Waltherson,-76.55734,39.33643,"(39.3364300000, -76.5573400000)",ROW/TOWNHO,1,2017
21,09/02/2017,16:55:00,3CF,600 HOMESTEAD ST,ROBBERY - COMMERCIAL,I,FIREARM,513,NORTHERN,Better Waverly,-76.60839,39.32712,"(39.3271200000, -76.6083900000)",RETAIL/SMA,1,2017
22,09/02/2017,16:00:00,4C,2000 N BENTALOU ST,AGG. ASSAULT,O,OTHER,731,WESTERN,Mondawmin,-76.65422,39.31091,"(39.3109100000, -76.6542200000)",STREET,1,2017
23,09/02/2017,15:46:00,3B,AV & REISTERSTOWN RD,ROBBERY - STREET,O,NaN,612,NORTHWESTERN,Park Circle,-76.66025,39.32887,"(39.3288700000, -76.6602500000)",STREET,1,2017
24,09/02/2017,15:00:00,6D,PY & ECHODALE AV,LARCENY FROM AUTO,O,NaN,415,NORTHEASTERN,Morgan State University,-76.57584,39.35489,"(39.3548900000, -76.5758400000)",STREET,1,2017
25,09/02/2017,15:00:00,6J,100 W LEXINGTON ST,LARCENY,I,NaN,111,CENTRAL,Downtown,-76.61729,39.29164,"(39.2916400000, -76.6172900000)",OFFICE BUI,1,2017
26,09/02/2017,14:50:00,4E,4700 MELBOURNE RD,COMMON ASSAULT,I,HANDS,833,SOUTHWESTERN,Beechfield,-76.69447,39.27224,"(39.2722400000, -76.6944700000)",ROW/TOWNHO,1,2017
27,09/02/2017,14:30:00,4E,300 LIGHT ST,COMMON ASSAULT,O,HANDS,112,CENTRAL,Inner Harbor,-76.61340,39.28544,"(39.2854400000, -76.6134000000)",STREET,1,2017
28,09/02/2017,14:25:00,5B,600 S STREEPER ST,BURGLARY,I,NaN,232,SOUTHEASTERN,Canton,-76.57639,39.28498,"(39.2849800000, -76.5763900000)",ROW/TOWNHO,1,2017
29,09/02/2017,13:48:00,4C,1700 E 30TH ST,AGG. ASSAULT,I,OTHER,411,NORTHEASTERN,Coldstream Homestead Mont,-76.59152,39.32537,"(39.3253700000, -76.5915200000)",ROW/TOWNHO,1,2017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4970,07/28/2017,18:00:00,6D,4200 AUDREY AVE,LARCENY FROM AUTO,O,NaN,913,SOUTHERN,Brooklyn,-76.60511,39.22957,"(39.2295700000, -76.6051100000)",STREET,1,2017
4971,07/28/2017,18:00:00,6D,900 E MADISON ST,LARCENY FROM AUTO,O,NaN,312,EASTERN,Oldtown,-76.60500,39.29904,"(39.2990400000, -76.6050000000)",STREET,1,2017
4972,07/28/2017,17:30:00,6D,2200 JEFFERSON ST,LARCENY FROM AUTO,O,NaN,321,EASTERN,CARE,-76.58592,39.29655,"(39.2965500000, -76.5859200000)",STREET,1,2017
4973,07/28/2017,17:30:00,5A,2400 E EAGER ST,BURGLARY,I,NaN,323,EASTERN,Milton-Montford,-76.58371,39.30177,"(39.3017700000, -76.5837100000)",ROW/TOWNHO,1,2017
4974,07/28/2017,17:30:00,5D,5000 QUEENSBERRY AVE,BURGLARY,NaN,NaN,614,NORTHWESTERN,Central Park Heights,-76.67121,39.34906,"(39.3490600000, -76.6712100000)",NaN,1,2017
4975,07/28/2017,17:20:00,5B,400 CALVIN AVE,BURGLARY,I,NaN,512,NORTHERN,Oakenshawe,-76.61077,39.33016,"(39.3301600000, -76.6107700000)",ROW/TOWNHO,1,2017
4976,07/28/2017,17:20:00,6F,500 N LINWOOD AVE,LARCENY,I,NaN,224,SOUTHEASTERN,Ellwood Park/Monument,-76.57652,39.29762,"(39.2976200000, -76.5765200000)",ROW/TOWNHO,1,2017
4977,07/28/2017,17:15:00,5A,3100 CLIFTMONT AVE,BURGLARY,I,NaN,434,NORTHEASTERN,Belair-Edison,-76.57503,39.31935,"(39.3193500000, -76.5750300000)",ROW/TOWNHO,1,2017
4978,07/28/2017,17:00:00,5A,3800 HILTON RD,BURGLARY,O,NaN,643,NORTHWESTERN,East Arlington,-76.66886,39.32935,"(39.3293500000, -76.6688600000)",HOUSE UNDE,1,2017
4979,07/28/2017,17:00:00,6E,4000 LINKWOOD RD,LARCENY,O,NaN,541,NORTHERN,Tuscany-Canterbury,-76.62462,39.33809,"(39.3380900000, -76.6246200000)",STREET,1,2017
4980,07/28/2017,17:00:00,7A,900 S CATON AVE,AUTO THEFT,NaN,NaN,832,SOUTHWESTERN,Violetville,-76.67137,39.27355,"(39.2735500000, -76.6713700000)",NaN,1,2017
4981,07/28/2017,17:00:00,5A,700 VENABLE AVE,BURGLARY,I,NaN,543,NORTHERN,Waverly,-76.60582,39.32914,"(39.3291400000, -76.6058200000)",ROW/TOWNHO,1,2017
4982,07/28/2017,17:00:00,6D,500 S FULTON AVE,LARCENY FROM AUTO,O,NaN,935,SOUTHERN,Carrollton Ridge,-76.64480,39.28192,"(39.2819200000, -76.6448000000)",STREET,1,2017
4983,07/28/2017,16:30:00,7C,2900 N CALVERT ST,AUTO THEFT,O,NaN,512,NORTHERN,Charles Village,-76.61464,39.32366,"(39.3236600000, -76.6146400000)",ALLEY,1,2017
4984,07/28/2017,16:30:00,5A,4600 HAMPNETT AVE,BURGLARY,NaN,NaN,421,NORTHEASTERN,Lauraville,-76.57106,39.34312,"(39.3431200000, -76.5710600000)",NaN,1,2017
4985,07/28/2017,16:30:00,6E,5500 CEDONIA AVE,LARCENY,O,NaN,441,NORTHEASTERN,Cedonia,-76.53290,39.33421,"(39.3342100000, -76.5329000000)",ALLEY,1,2017
4986,07/28/2017,16:15:00,6D,3800 GREENWAY,LARCENY FROM AUTO,O,NaN,542,NORTHERN,Guilford,-76.61344,39.33493,"(39.3349300000, -76.6134400000)",STREET,1,2017
4987,07/28/2017,16:07:00,5D,1100 WHITMORE AVE,BURGLARY,NaN,NaN,723,WESTERN,Bridgeview/Greenlawn,-76.65822,39.30060,"(39.3006000000, -76.6582200000)",NaN,1,2017
4988,07/28/2017,16:00:00,6D,900 NOTTINGHAM RD,LARCENY FROM AUTO,I,NaN,823,SOUTHWESTERN,West Hills,-76.70666,39.29771,"(39.2977100000, -76.7066600000)",PARKING LO,1,2017
4989,07/28/2017,16:00:00,5A,500 W HOFFMAN ST,BURGLARY,NaN,NaN,123,CENTRAL,Upton,-76.62666,39.30025,"(39.3002500000, -76.6266600000)",NaN,1,2017
4990,07/28/2017,16:00:00,6E,4000 Biddison Ln,LARCENY,NaN,NaN,426,NORTHEASTERN,Waltherson,-76.55412,39.33758,"(39.3375800000, -76.5541200000)",NaN,1,2017
4991,07/28/2017,16:00:00,6J,3500 DOLFIELD AVE,LARCENY,I,NaN,643,NORTHWESTERN,Ashburton,-76.67418,39.33459,"(39.3345900000, -76.6741800000)",CONVENIENC,1,2017
4992,07/28/2017,15:47:00,9S,2000 BEECHWOOD AV,SHOOTING,Outside,FIREARM,821,SOUTHWESTERN,Franklintown,-76.70579,39.30535,"(39.3053500000, -76.7057900000)",Street,1,2017
4993,07/28/2017,15:05:00,4A,HEIGHTS AV & GWYNN OAK AV,AGG. ASSAULT,O,FIREARM,622,NORTHWESTERN,Howard Park,-76.69572,39.33140,"(39.3314000000, -76.6957200000)",STREET,1,2017
4994,07/28/2017,15:05:00,4A,HEIGHTS AV & GWYNN OAK AV,AGG. ASSAULT,O,FIREARM,622,NORTHWESTERN,Howard Park,-76.69572,39.33140,"(39.3314000000, -76.6957200000)",STREET,1,2017
4995,07/28/2017,15:00:00,5A,2900 RUECKERT AVE,BURGLARY,I,NaN,421,NORTHEASTERN,Lauraville,-76.56659,39.34885,"(39.3488500000, -76.5665900000)",ROW/TOWNHO,1,2017
4996,07/28/2017,15:00:00,6D,ST & TOONE ST,LARCENY FROM AUTO,O,NaN,232,SOUTHEASTERN,Canton,-76.56756,39.27845,"(39.2784500000, -76.5675600000)",STREET,1,2017
4997,07/28/2017,15:00:00,6D,2600 PENNSYLVANIA AVE,LARCENY FROM AUTO,O,NaN,733,WESTERN,Penn North,-76.64398,39.31127,"(39.3112700000, -76.6439800000)",STREET,1,2017
4998,07/28/2017,15:00:00,6E,4000 HILLEN RD,LARCENY,O,NaN,412,NORTHEASTERN,Hillen,-76.58833,39.33889,"(39.3388900000, -76.5883300000)",STREET,1,2017
4999,07/28/2017,14:46:00,6D,4500 EDMONDSON AVE,LARCENY FROM AUTO,O,NaN,822,SOUTHWESTERN,Rognel Heights,-76.69365,39.29346,"(39.2934600000, -76.6936500000)",PARKING LO,1,2017

In [8]:
# types = baltimore__crime_df["year"].value_counts()
# types

In [9]:
baltimore__crime_df["District"]= baltimore__crime_df["District"].replace("NORTHEASTERN","NE")
baltimore__crime_df["District"]= baltimore__crime_df["District"].replace("SOUTHEASTERN","SE")
baltimore__crime_df["District"]= baltimore__crime_df["District"].replace("SOUTHERN","S")
baltimore__crime_df["District"]= baltimore__crime_df["District"].replace("NORTHERN","N")
baltimore__crime_df["District"]= baltimore__crime_df["District"].replace("CENTRAL","C")
baltimore__crime_df["District"]= baltimore__crime_df["District"].replace("NORTHWESTERN","NW")
baltimore__crime_df["District"]= baltimore__crime_df["District"].replace("SOUTHWESTERN","SW")
baltimore__crime_df["District"]= baltimore__crime_df["District"].replace("EASTERN","E")
baltimore__crime_df["District"]= baltimore__crime_df["District"].replace("WESTERN","W")

In [10]:
baltimore__crime_df

,CrimeDate,CrimeTime,CrimeCode,Location,Description,Inside/Outside,Weapon,Post,District,Neighborhood,Longitude,Latitude,Location 1,Premise,Total Incidents,year
0,09/02/2017,23:30:00,3JK,4200 AUDREY AVE,ROBBERY - RESIDENCE,I,KNIFE,913,S,Brooklyn,-76.60541,39.22951,"(39.2295100000, -76.6054100000)",ROW/TOWNHO,1,2017
1,09/02/2017,23:00:00,7A,800 NEWINGTON AVE,AUTO THEFT,O,NaN,133,C,Reservoir Hill,-76.63217,39.31360,"(39.3136000000, -76.6321700000)",STREET,1,2017
2,09/02/2017,22:53:00,9S,600 RADNOR AV,SHOOTING,Outside,FIREARM,524,N,Winston-Govans,-76.60697,39.34768,"(39.3476800000, -76.6069700000)",Street,1,2017
3,09/02/2017,22:50:00,4C,1800 RAMSAY ST,AGG. ASSAULT,I,OTHER,934,S,Carrollton Ridge,-76.64526,39.28315,"(39.2831500000, -76.6452600000)",ROW/TOWNHO,1,2017
4,09/02/2017,22:31:00,4E,100 LIGHT ST,COMMON ASSAULT,O,HANDS,113,C,Downtown West,-76.61365,39.28756,"(39.2875600000, -76.6136500000)",STREET,1,2017
5,09/02/2017,22:00:00,5A,CHERRYCREST RD,BURGLARY,I,NaN,922,S,Cherry Hill,-76.62131,39.24867,"(39.2486700000, -76.6213100000)",ROW/TOWNHO,1,2017
6,09/02/2017,21:15:00,1F,3400 HARMONY CT,HOMICIDE,Outside,FIREARM,232,SE,Canton,-76.56827,39.28202,"(39.2820200000, -76.5682700000)",Street,1,2017
7,09/02/2017,21:35:00,3B,400 W LANVALE ST,ROBBERY - STREET,O,NaN,123,C,Upton,-76.62789,39.30254,"(39.3025400000, -76.6278900000)",STREET,1,2017
8,09/02/2017,21:00:00,4C,2300 LYNDHURST AVE,AGG. ASSAULT,O,OTHER,641,NW,Windsor Hills,-76.68365,39.31370,"(39.3137000000, -76.6836500000)",STREET,1,2017
9,09/02/2017,21:00:00,4E,1200 N ELLWOOD AVE,COMMON ASSAULT,I,HANDS,332,E,Berea,-76.57419,39.30551,"(39.3055100000, -76.5741900000)",ROW/TOWNHO,1,2017
10,09/02/2017,21:00:00,4C,2300 LYNDHURST AVE,AGG. ASSAULT,O,OTHER,641,NW,Windsor Hills,-76.68365,39.31370,"(39.3137000000, -76.6836500000)",STREET,1,2017
11,09/02/2017,20:56:00,3CF,3600 EDMONDSON AVE,ROBBERY - COMMERCIAL,I,FIREARM,844,SW,Edgewood,-76.67759,39.29402,"(39.2940200000, -76.6775900000)",RETAIL/SMA,1,2017
12,09/02/2017,20:55:00,6C,5100 PARK HEIGHTS AVE,LARCENY,NaN,NaN,614,NW,Central Park Heights,-76.67511,39.34861,"(39.3486100000, -76.6751100000)",NaN,1,2017
13,09/02/2017,20:10:00,4C,3900 GWYNNS FALLS PKWY,AGG. ASSAULT,O,OTHER,641,NW,Windsor Hills,-76.68169,39.31400,"(39.3140000000, -76.6816900000)",STREET,1,2017
14,09/02/2017,20:00:00,6D,5500 SUMMERFIELD AVE,LARCENY FROM AUTO,O,NaN,444,NE,Frankford,-76.54270,39.33288,"(39.3328800000, -76.5427000000)",YARD,1,2017
15,09/02/2017,19:52:00,5D,2200 VAN DEMAN ST,BURGLARY,I,NaN,243,SE,Holabird Industrial Park,-76.53557,39.26533,"(39.2653300000, -76.5355700000)",OTHER - IN,1,2017
16,09/02/2017,18:08:00,9S,1200 E LAFAYETTE AV,SHOOTING,Outside,FIREARM,343,E,Oliver,-76.60246,39.31038,"(39.3103800000, -76.6024600000)",Street,1,2017
17,09/02/2017,18:08:00,1F,1200 E LAFAYETTE AV,HOMICIDE,Outside,FIREARM,343,E,Oliver,-76.60246,39.31038,"(39.3103800000, -76.6024600000)",Street,1,2017
18,09/02/2017,18:16:00,4E,1000 N EUTAW ST,COMMON ASSAULT,O,HANDS,132,C,Madison Park,-76.62256,39.30083,"(39.3008300000, -76.6225600000)",STREET,1,2017
19,09/02/2017,18:00:00,6G,100 S BROADWAY,LARCENY,I,NaN,212,SE,Washington Hill,-76.59390,39.29020,"(39.2902000000, -76.5939000000)",CONVENIENC,1,2017
20,09/02/2017,17:17:00,5A,4000 RIDGECROFT RD,BURGLARY,I,NaN,426,NE,Waltherson,-76.55734,39.33643,"(39.3364300000, -76.5573400000)",ROW/TOWNHO,1,2017
21,09/02/2017,16:55:00,3CF,600 HOMESTEAD ST,ROBBERY - COMMERCIAL,I,FIREARM,513,N,Better Waverly,-76.60839,39.32712,"(39.3271200000, -76.6083900000)",RETAIL/SMA,1,2017
22,09/02/2017,16:00:00,4C,2000 N BENTALOU ST,AGG. ASSAULT,O,OTHER,731,W,Mondawmin,-76.65422,39.31091,"(39.3109100000, -76.6542200000)",STREET,1,2017
23,09/02/2017,15:46:00,3B,AV & REISTERSTOWN RD,ROBBERY - STREET,O,NaN,612,NW,Park Circle,-76.66025,39.32887,"(39.3288700000, -76.6602500000)",STREET,1,2017
24,09/02/2017,15:00:00,6D,PY & ECHODALE AV,LARCENY FROM AUTO,O,NaN,415,NE,Morgan State University,-76.57584,39.35489,"(39.3548900000, -76.5758400000)",STREET,1,2017
25,09/02/2017,15:00:00,6J,100 W LEXINGTON ST,LARCENY,I,NaN,111,C,Downtown,-76.61729,39.29164,"(39.2916400000, -76.6172900000)",OFFICE BUI,1,2017
26,09/02/2017,14:50:00,4E,4700 MELBOURNE RD,COMMON ASSAULT,I,HANDS,833,SW,Beechfield,-76.69447,39.27224,"(39.2722400000, -76.6944700000)",ROW/TOWNHO,1,2017
27,09/02/2017,14:30:00,4E,300 LIGHT ST,COMMON ASSAULT,O,HANDS,112,C,Inner Harbor,-76.61340,39.28544,"(39.2854400000, -76.6134000000)",STREET,1,2017
28,09/02/2017,14:25:00,5B,600 S STREEPER ST,BURGLARY,I,NaN,232,SE,Canton,-76.57639,39.28498,"(39.2849800000, -76.5763900000)",ROW/TOWNHO,1,2017
29,09/02/2017,13:48:00,4C,1700 E 30TH ST,AGG. ASSAULT,I,OTHER,411,NE,Coldstream Homestead Mont,-76.59152,39.32537,"(39.3253700000, -76.5915200000)",ROW/TOWNHO,1,2017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4970,07/28/2017,18:00:00,6D,4200 AUDREY AVE,LARCENY FROM AUTO,O,NaN,913,S,Brooklyn,-76.60511,39.22957,"(39.2295700000, -76.6051100000)",STREET,1,2017
4971,07/28/2017,18:00:00,6D,900 E MADISON ST,LARCENY FROM AUTO,O,NaN,312,E,Oldtown,-76.60500,39.29904,"(39.2990400000, -76.6050000000)",STREET,1,2017
4972,07/28/2017,17:30:00,6D,2200 JEFFERSON ST,LARCENY FROM AUTO,O,NaN,321,E,CARE,-76.58592,39.29655,"(39.2965500000, -76.5859200000)",STREET,1,2017
4973,07/28/2017,17:30:00,5A,2400 E EAGER ST,BURGLARY,I,NaN,323,E,Milton-Montford,-76.58371,39.30177,"(39.3017700000, -76.5837100000)",ROW/TOWNHO,1,2017
4974,07/28/2017,17:30:00,5D,5000 QUEENSBERRY AVE,BURGLARY,NaN,NaN,614,NW,Central Park Heights,-76.67121,39.34906,"(39.3490600000, -76.6712100000)",NaN,1,2017
4975,07/28/2017,17:20:00,5B,400 CALVIN AVE,BURGLARY,I,NaN,512,N,Oakenshawe,-76.61077,39.33016,"(39.3301600000, -76.6107700000)",ROW/TOWNHO,1,2017
4976,07/28/2017,17:20:00,6F,500 N LINWOOD AVE,LARCENY,I,NaN,224,SE,Ellwood Park/Monument,-76.57652,39.29762,"(39.2976200000, -76.5765200000)",ROW/TOWNHO,1,2017
4977,07/28/2017,17:15:00,5A,3100 CLIFTMONT AVE,BURGLARY,I,NaN,434,NE,Belair-Edison,-76.57503,39.31935,"(39.3193500000, -76.5750300000)",ROW/TOWNHO,1,2017
4978,07/28/2017,17:00:00,5A,3800 HILTON RD,BURGLARY,O,NaN,643,NW,East Arlington,-76.66886,39.32935,"(39.3293500000, -76.6688600000)",HOUSE UNDE,1,2017
4979,07/28/2017,17:00:00,6E,4000 LINKWOOD RD,LARCENY,O,NaN,541,N,Tuscany-Canterbury,-76.62462,39.33809,"(39.3380900000, -76.6246200000)",STREET,1,2017
4980,07/28/2017,17:00:00,7A,900 S CATON AVE,AUTO THEFT,NaN,NaN,832,SW,Violetville,-76.67137,39.27355,"(39.2735500000, -76.6713700000)",NaN,1,2017
4981,07/28/2017,17:00:00,5A,700 VENABLE AVE,BURGLARY,I,NaN,543,N,Waverly,-76.60582,39.32914,"(39.3291400000, -76.6058200000)",ROW/TOWNHO,1,2017
4982,07/28/2017,17:00:00,6D,500 S FULTON AVE,LARCENY FROM AUTO,O,NaN,935,S,Carrollton Ridge,-76.64480,39.28192,"(39.2819200000, -76.6448000000)",STREET,1,2017
4983,07/28/2017,16:30:00,7C,2900 N CALVERT ST,AUTO THEFT,O,NaN,512,N,Charles Village,-76.61464,39.32366,"(39.3236600000, -76.6146400000)",ALLEY,1,2017
4984,07/28/2017,16:30:00,5A,4600 HAMPNETT AVE,BURGLARY,NaN,NaN,421,NE,Lauraville,-76.57106,39.34312,"(39.3431200000, -76.5710600000)",NaN,1,2017
4985,07/28/2017,16:30:00,6E,5500 CEDONIA AVE,LARCENY,O,NaN,441,NE,Cedonia,-76.53290,39.33421,"(39.3342100000, -76.5329000000)",ALLEY,1,2017
4986,07/28/2017,16:15:00,6D,3800 GREENWAY,LARCENY FROM AUTO,O,NaN,542,N,Guilford,-76.61344,39.33493,"(39.3349300000, -76.6134400000)",STREET,1,2017
4987,07/28/2017,16:07:00,5D,1100 WHITMORE AVE,BURGLARY,NaN,NaN,723,W,Bridgeview/Greenlawn,-76.65822,39.30060,"(39.3006000000, -76.6582200000)",NaN,1,2017
4988,07/28/2017,16:00:00,6D,900 NOTTINGHAM RD,LARCENY FROM AUTO,I,NaN,823,SW,West Hills,-76.70666,39.29771,"(39.2977100000, -76.7066600000)",PARKING LO,1,2017
4989,07/28/2017,16:00:00,5A,500 W HOFFMAN ST,BURGLARY,NaN,NaN,123,C,Upton,-76.62666,39.30025,"(39.3002500000, -76.6266600000)",NaN,1,2017
4990,07/28/2017,16:00:00,6E,4000 Biddison Ln,LARCENY,NaN,NaN,426,NE,Waltherson,-76.55412,39.33758,"(39.3375800000, -76.5541200000)",NaN,1,2017
4991,07/28/2017,16:00:00,6J,3500 DOLFIELD AVE,LARCENY,I,NaN,643,NW,Ashburton,-76.67418,39.33459,"(39.3345900000, -76.6741800000)",CONVENIENC,1,2017
4992,07/28/2017,15:47:00,9S,2000 BEECHWOOD AV,SHOOTING,Outside,FIREARM,821,SW,Franklintown,-76.70579,39.30535,"(39.3053500000, -76.7057900000)",Street,1,2017
4993,07/28/2017,15:05:00,4A,HEIGHTS AV & GWYNN OAK AV,AGG. ASSAULT,O,FIREARM,622,NW,Howard Park,-76.69572,39.33140,"(39.3314000000, -76.6957200000)",STREET,1,2017
4994,07/28/2017,15:05:00,4A,HEIGHTS AV & GWYNN OAK AV,AGG. ASSAULT,O,FIREARM,622,NW,Howard Park,-76.69572,39.33140,"(39.3314000000, -76.6957200000)",STREET,1,2017
4995,07/28/2017,15:00:00,5A,2900 RUECKERT AVE,BURGLARY,I,NaN,421,NE,Lauraville,-76.56659,39.34885,"(39.3488500000, -76.5665900000)",ROW/TOWNHO,1,2017
4996,07/28/2017,15:00:00,6D,ST & TOONE ST,LARCENY FROM AUTO,O,NaN,232,SE,Canton,-76.56756,39.27845,"(39.2784500000, -76.5675600000)",STREET,1,2017
4997,07/28/2017,15:00:00,6D,2600 PENNSYLVANIA AVE,LARCENY FROM AUTO,O,NaN,733,W,Penn North,-76.64398,39.31127,"(39.3112700000, -76.6439800000)",STREET,1,2017
4998,07/28/2017,15:00:00,6E,4000 HILLEN RD,LARCENY,O,NaN,412,NE,Hillen,-76.58833,39.33889,"(39.3388900000, -76.5883300000)",STREET,1,2017
4999,07/28/2017,14:46:00,6D,4500 EDMONDSON AVE,LARCENY FROM AUTO,O,NaN,822,SW,Rognel Heights,-76.69365,39.29346,"(39.2934600000, -76.6936500000)",PARKING LO,1,2017

In [11]:
merge_table = pd.merge(baltimore__911_df, baltimore__crime_df, on="District")
merge_table.head()

,callDateTime,priority,District,description,callNumber,incidentLocation,location,CrimeDate,CrimeTime,CrimeCode,...,Inside/Outside,Weapon,Post,Neighborhood,Longitude,Latitude,Location 1,Premise,Total Incidents,year
0,2015-07-13 10:46:00,Medium,SW,AUTO THEFT,P151941006,3500 CLIFTON AV,"(39.3112130,-76.6763150)",09/02/2017,20:56:00,3CF,...,I,FIREARM,844,Edgewood,-76.67759,39.29402,"(39.2940200000, -76.6775900000)",RETAIL/SMA,1,2017
1,2015-07-13 10:46:00,Medium,SW,AUTO THEFT,P151941006,3500 CLIFTON AV,"(39.3112130,-76.6763150)",09/02/2017,14:50:00,4E,...,I,HANDS,833,Beechfield,-76.69447,39.27224,"(39.2722400000, -76.6944700000)",ROW/TOWNHO,1,2017
2,2015-07-13 10:46:00,Medium,SW,AUTO THEFT,P151941006,3500 CLIFTON AV,"(39.3112130,-76.6763150)",09/02/2017,11:18:00,3K,...,I,NaN,842,Saint Josephs,-76.67387,39.28575,"(39.2857500000, -76.6738700000)",ROW/TOWNHO,1,2017
3,2015-07-13 10:46:00,Medium,SW,AUTO THEFT,P151941006,3500 CLIFTON AV,"(39.3112130,-76.6763150)",09/02/2017,09:00:00,5A,...,I,NaN,823,Ten Hills,-76.69688,39.28553,"(39.2855300000, -76.6968800000)",APT/CONDO,1,2017
4,2015-07-13 10:46:00,Medium,SW,AUTO THEFT,P151941006,3500 CLIFTON AV,"(39.3112130,-76.6763150)",09/02/2017,08:09:00,6J,...,I,NaN,832,Violetville,-76.67980,39.27101,"(39.2710100000, -76.6798000000)",CARRY OUT,1,2017

## merge_table.columns

In [37]:
merge_table = pd.DataFrame({
    "CrimeDate":merge_table["CrimeDate"],
    "CrimeTime":merge_table["CrimeTime"],
    "District":merge_table["District"],
    "Description":merge_table["Description"],
    "Weapon":merge_table["Weapon"],
    "Total Incidents":merge_table["Total Incidents"]
})
merge_table.head()

,CrimeDate,CrimeTime,District,Description,Weapon,Total Incidents
0,09/02/2017,20:56:00,SW,ROBBERY - COMMERCIAL,FIREARM,1
1,09/02/2017,14:50:00,SW,COMMON ASSAULT,HANDS,1
2,09/02/2017,11:18:00,SW,ROBBERY - RESIDENCE,NaN,1
3,09/02/2017,09:00:00,SW,BURGLARY,NaN,1
4,09/02/2017,08:09:00,SW,LARCENY,NaN,1

In [39]:
merge_table = merge_table.dropna()
merge_table.head()

,CrimeDate,CrimeTime,District,Description,Weapon,Total Incidents
0,09/02/2017,20:56:00,SW,ROBBERY - COMMERCIAL,FIREARM,1
1,09/02/2017,14:50:00,SW,COMMON ASSAULT,HANDS,1
5,09/02/2017,06:15:00,SW,COMMON ASSAULT,HANDS,1
8,09/01/2017,19:30:00,SW,COMMON ASSAULT,HANDS,1
10,09/01/2017,14:58:00,SW,AGG. ASSAULT,OTHER,1